HOME_ROUTE = "/"
ABOUT_ROUTE = "/about"
CONTACT_ROUTE = "/contact"
CONTACTS_ROUTE = "/contact/list"
PRICING_ROUTE = "/pricing"
BLOG_POSTS_ROUTE = "/blog"
CREATE_BLOG_POST_ROUTE = "/blog/posting"
BLOG_POST_DETAIL_ROUTE = "/blog/posting/[post_id]"
